# If set to false, the plugin will not register any listeners or send messages
enabled: true
# These messages are shown in the console or as command feedback
system_messages:
  # Message sent to the console when the plugin is enabled or disabled
  lifecycle:
    enable: "Enabled Letters v<plugin_version>"
    disable: "Disabled Letters v<plugin_version>"
  # Message sent to the console before the plugin disables itself due to a config option
  status:
    disabled: "Plugin is disabled in config."
  # Message sent to the console when the plugin checks for dependency plugins
  dependencies:
    placeholder_api:
      found: "PlaceholderAPI detected. Additional placeholders will work"
      not_found: "PlaceholderAPI not detected. Additional placeholders will not work"
    luckperms:
      found: "LuckPerms detected. Group-based messages will work"
      not_found: "LuckPerms not detected. Group-based messages will not work"